// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGfcKY4NiFOKLKQVmhkQleId_MqYUgFQk',
    appId: '1:263995831362:web:e0b217c7ff462fd42569db',
    messagingSenderId: '263995831362',
    projectId: 'hotel-kitchen-management-app',
    authDomain: 'hotel-kitchen-management-app.firebaseapp.com',
    storageBucket: 'hotel-kitchen-management-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRkSgeq2PhagOw0-7OzA_sBsUh7fquQQ',
    appId: '1:263995831362:android:be3bcd2b2209c72d2569db',
    messagingSenderId: '263995831362',
    projectId: 'hotel-kitchen-management-app',
    storageBucket: 'hotel-kitchen-management-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzcBvjhSWpYMT-ylLX0dDoEkn9Fz16HHk',
    appId: '1:263995831362:ios:6f0f368d8c9977de2569db',
    messagingSenderId: '263995831362',
    projectId: 'hotel-kitchen-management-app',
    storageBucket: 'hotel-kitchen-management-app.appspot.com',
    iosBundleId: 'com.example.hotelKitchenManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzcBvjhSWpYMT-ylLX0dDoEkn9Fz16HHk',
    appId: '1:263995831362:ios:a3aa720840dccc902569db',
    messagingSenderId: '263995831362',
    projectId: 'hotel-kitchen-management-app',
    storageBucket: 'hotel-kitchen-management-app.appspot.com',
    iosBundleId: 'com.example.hotelKitchenManagementApp.RunnerTests',
  );
}
